stages:
  - build
  - deploy

default:
  image: python:3.10-alpine

workflow:
  rules:
    - if: $CI_COMMENT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "main"

build_docs:
  stage: build
  before_script:
    - apk update
    - apk add --no-cache make git bash
    - pip install -r docs/requirements.txt
    - git fetch --prune --unshallow --tags # tags needed to generate version displayed in the website
  script:
    - make docs
  artifacts:
    paths:
      - build/docs

pages:
  stage: deploy
  script:
    - mkdir public
    - mv build/docs/* public
  artifacts:
    paths:
      - public
