[package]
name = "tecomp"
version = "0.1.0"
description = "TeX compilation backend interface for TexEdit"

edition = "2018"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
notify = "6.1.1"
