name: Build and deploy documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # this is broken (https://github.com/actions/checkout/issues/1471). very helpful :) -- so we fetch tags seperately in the next step
          fetch-tags: true

      - run: git fetch --prune --unshallow --tags

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r ${GITHUB_WORKSPACE}/docs/requirements.txt

      - name: Build docs
        run: make docs
          && touch ${GITHUB_WORKSPACE}/build/docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/docs
